# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd ./webapp
    npm install
  displayName: 'Installing Dependencies' 

- script: |
    cd ./webapp
    npm run build
  displayName: 'Building'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'sd-webapp-service-connection'
    appType: 'webAppLinux'
    appName: 'sd-lrp-research'
    package: '$(System.DefaultWorkingDirectory)/webapp'
    startUpCommand: 'npm run start'
    runtimeStack: 'NODE|18-lts'
    deploymentMethod: 'runFromPackage'